# Generated by Django 3.1.1 on 2020-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Warnung', 'Warnung'), ('Fehler', 'Fehler')], default='OK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Warnung', 'Warnung'), ('Fehler', 'Fehler')], default='OK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sprinkler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Warnung', 'Warnung'), ('Fehler', 'Fehler')], default='OK', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
