# Generated by Django 3.1.1 on 2020-10-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200924_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinkler',
            name='curr_active',
            field=models.BooleanField(default=False),
        ),
    ]
