# Generated by Django 3.1.1 on 2020-10-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_sprinkler_curr_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='curr_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='curr_active',
            field=models.BooleanField(default=False),
        ),
    ]
