# Generated by Django 3.1.1 on 2020-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201008_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('Warnung', 'Warnung'), ('Fehler', 'Fehler')], default='OK', max_length=10),
        ),
    ]
