# Generated by Django 3.1.1 on 2020-10-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20201008_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(default='Beschreibung', max_length=3000),
        ),
    ]
