# Generated by Django 3.1 on 2020-10-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20201009_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='automation',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='pump',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='sprinkler',
        ),
        migrations.AddField(
            model_name='plan',
            name='automation_rain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='automation_sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='timespace_rain_forecast',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='pump',
            name='contr_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pump',
            name='current_workload',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pump',
            name='flow_capacity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='contr_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='moisture_threshold',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprinkler',
            name='contr_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprinkler',
            name='flow_capacity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Warnung', 'Warnung'), ('Fehler', 'Fehler')], default='OK', max_length=10)),
                ('contr_id', models.IntegerField()),
                ('curr_active', models.BooleanField(default=False)),
                ('valve_threshold', models.IntegerField(default=100)),
                ('pump_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.pump')),
                ('sensor_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='valve',
            field=models.ManyToManyField(to='webapp.Valve'),
        ),
        migrations.AddField(
            model_name='sprinkler',
            name='valve_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.valve'),
        ),
    ]
