# Generated by Django 3.1.1 on 2020-10-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20201019_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='current_workload',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
